name: lms
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by\ a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionStringke while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#version: 1.0.0-beta.1.2+4
version: 1.0.0+5

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.7 # Reactive dart programming.
  dio: ^5.4.3+1 # Network API library
  fluttertoast: ^8.2.5 # Toast
  shared_preferences: ^2.0.15 # Shared Preferences
  cookie_jar: ^4.0.8 # Manage Cookiesbuild rea
  path_provider: ^2.0.11 # Open device path storage
#  sqflite: ^2.2.2 # Local Database
#  android_intent: ^2.0.2 # Open Location Service
  permission_handler: ^11.3.1 # Flutter Permission handler Plugin
  device_info_plus: ^9.1.2 # Get Android and iOS device info.
  connectivity_plus: ^6.0.3 # Check Network Connectivity
  intl: ^0.18.1
  path: ^1.8.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_typeahead: ^5.2.0
  dio_cookie_manager: ^3.1.1
  google_sign_in: ^6.2.1 #Login with google using firebase
  firebase_auth: ^4.2.3 #Firebase authentication
  # flutter_facebook_login: ^3.0.0 #Login with facebook
#  flutter_facebook_auth: ^5.0.6
  http: ^1.2.0
  #pin_entry_text_field: ^0.1.4
  #  passcode_screen: ^1.2.0
  pin_code_fields: ^8.0.1
  solid_bottom_sheet: ^0.1.10
  url_launcher: ^6.1.7
  introduction_screen: ^3.1.1
  another_flushbar: ^1.12.29
  sign_in_with_apple: ^5.0.0
  flutter_keychain: ^2.2.1
#  mobile_number: ^1.0.2
#  search_widget: ^1.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  local_auth: ^2.1.2 #Biometric and FingerPrint Authentication - Visible auth dialog
#  flutter_local_auth_invisible: ^2.0.0 #Biometric and FingerPrint Authentication - Invisible auth dialog
#  get_it: ^7.2.0
  firebase_messaging: ^14.2.0
  firebase_analytics: ^10.0.8
  firebase_crashlytics: ^3.0.8
  firebase_core: ^2.4.0
  flutter_local_notifications: ^17.2.3
#  step_progress_indicator: ^1.0.1 9.1.2+1
#  sliding_up_panel: ^2.0.0+1
  #  flutter_svg: ^0.17.0
#  dashed_container: ^1.0.1
#  flutter_rating_bar: ^4.0.0
  #  sms_autofill: ^1.2.4
  #  sms_otp_auto_verify: ^1.2.2
#  dotted_border: ^2.0.0+1
  package_info_plus: ^6.0.0 # Package Info
  dotted_line: ^3.1.0
  webview_flutter: ^4.5.0
  sms_autofill: ^2.4.0
  # grouped_buttons: ^1.0.4
#  documents_picker: ^1.0.0 #need_to_remove
  razorpay_flutter: ^1.3.0
  flutter_html: ^3.0.0-beta.2
 # device_preview: ^1.1.0
#  syncfusion_flutter_charts: ^19.2.55+1
#  syncfusion_flutter_pdfviewer: ^20.3.61-beta
  flutter_downloader: ^1.9.1
  alice: ^0.4.2
  #flutter_alice: ^1.0.0
  # ext_storage: ^1.0.3
#  flutter_stetho: ^0.5.2
#  flutter_stetho:
#   git:
#    url: https://github.com/jasonlewicki/flutter_stetho.git
#    ref: master
#    publish_to: none #need_to_remove
#  charts_flutter: ^0.11.0
  shimmer: ^3.0.0
  flutter_switch: ^0.3.2
#  slide_countdown_clock: ^1.0.3
#  flutter_jailbreak_detection: ^1.7.0
  safe_device: ^1.1.2
  youtube_player_flutter: ^9.0.1
  share_plus: ^9.0.0
  image_picker: ^1.0.8
  image_cropper: ^5.0.1
  flutter_slidable: ^3.1.0
#  flutter_login_facebook: ^1.1.0
#  device_apps: ^2.1.1
#  sms_autofill: ^2.0.1
  cron: ^0.6.0
#  new_version: ^0.3.1
  firebase_in_app_messaging: ^0.7.0+9
  page_indicator: ^0.4.1
#  simple_tooltip: ^1.0.0
#  flutter_inappwebview: ^5.1.0+4
  uni_links: ^0.5.1
  advance_pdf_viewer: ^2.0.1
  awesome_dropdown:
    git:
      url: https://github.com/aayushkedawat1/Flutter-CustomizableDropDown.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
    


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec



# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/setting_icon.png
    - assets/images/warning_icon.png
    - assets/images/right_arrow_icon.png
    - assets/images/percentage_icon.png
    - assets/images/active_loan_icon.png
    - assets/images/increase_loan.png
    - assets/images/credit_score_icon.png
    - assets/images/statement.png
    - assets/images/rewards_icon.png
    - assets/images/top_up_icon.png
    - assets/images/increase_loan_icon.png
    - assets/images/pay_now.png
    - assets/images/faq.png
    - assets/images/privacy_policy.png
    - assets/images/terms_of_use.png
    - assets/images/tutorial5.png
    - assets/images/youtube.png
    - assets/images/security_settings_icon.png
    - assets/images/manage_kyc_icon.png
    - assets/images/reminder_notifications_icon.png
    - assets/images/saved_addresses_icon.png
    - assets/images/signout_icon.png
    - assets/images/payment_settings_icon.png
    - assets/images/right_arrow_imageicon.png
    - assets/images/down_arrow_image_icon.png
    - assets/images/camera_icon.png
    - assets/images/change_pin_submit_icon.png
    - assets/images/account_settings_edit_icon.png
    - assets/images/account_details.png
    - assets/images/demat_details.png
    - assets/images/manage_settings_icon.png
    - assets/images/success_notification.png
    - assets/images/warning_notification.png
    - assets/images/delete_notification.png
    - assets/images/timer.png
    - assets/images/approved_security_list_icon.png
    - assets/images/toggle_off.png
    - assets/images/drop_down_arrow_image.png
    - assets/images/pnb_bank_logo.png
    - assets/images/lender_T.png
    - assets/images/lender_C.png
    - assets/images/lender_B.png
    - assets/images/up_arrow.png
    - assets/images/cross_icon.png
    - assets/images/i_icon_with_circle.png
    - assets/images/delete_icon_bg_red.png
    - assets/images/biometric.png
    - assets/images/cams_email_id.png

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-light.ttf
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
